"""create Users, user_macro_targets, and food_logs tables

Revision ID: 3ad257417fe6
Revises: b6d96d4450e7
Create Date: 2026-09-19 14:32:20.232033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad257417fe6'
down_revision: Union[str, Sequence[str], None] = 'b6d96d4450e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth_service'
    )
    op.create_table('food_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_served', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nutrition_service'
    )
    op.create_table('user_macro_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_protein_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_carbs_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_fat_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nutrition_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_macro_targets', schema='nutrition_service')
    op.drop_table('food_logs', schema='nutrition_service')
    op.drop_table('users', schema='auth_service')
    # ### end Alembic commands ###
